apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: User
  name: aws-registry-credential
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secret-writer
  apiGroup: rbac.authorization.k8s.io
